### ISSUE TITLE
httpIngressPorts is not applicable

### ISSUE THREAD

**Issue by ygree** [lightbend/reactive-cli#106] opened 2018-02-02 01:01 UTC
The `httpIngressPorts` property doesn't seem correct in first place. There seem to be no such a property for Ingress.

**Comment by longshorej** [comment] 2018-02-05 16:57
Yeah, I think that is appropriate for MarathonLB but not K8s. I'll leave this open for now; we may extend the project to generate Marathon JSON for example.

**Comment by alanngai** [comment] 2018-05-26 00:38
@mitkus can you comment on whether this issue is still relevant given our Marathon support?  Should it be marked done?

**Comment by eed3si9n** [comment] 2019-02-13 23:35
I am going to close this as a duplicate of #158.

As per Marathon, ingressPort is not read when defining the `servicePort` here - https://github.com/lightbend/reactive-cli/blob/v1.7.1/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/marathon/package.scala#L202-L203

**Closed by eed3si9n** 2019-02-13 23:35 UTC
Labels: backlog, reactive-cli
